// src/components/Button/Button.tsx
import classNames from 'classnames';
import type { ButtonProps } from './Button.types';
import './Button.css';

export const Button: React.FC<ButtonProps> = ({
  type,
  href,
  variants = [],
  children,
  className,
  ...props
}) => {
  const Component = href ? 'a' : 'button';
  const variantClasses = classNames(variants.map((variant: string) => `c-button--${variant}`));

  return (
    <Component
      {...props}
      className={classNames('c-button', variantClasses, className)}
      type={!href ? type : undefined}
      href={href}
    >
      {children}
    </Component>
  );
};
export default Button;

// src/components/Button/Button.vue
<template>
  <component
    :is="htmlTag"
    :type="!href && type ? type : undefined"
    :class="['c-button', variantClasses]"
    :href="href"
  >
    <span class="c-button__label" v-if="hasSlot('default')">
      <slot name="default" />
    </span>
    <span class="c-button__icon" v-if="hasSlot('icon')">
      <slot name="icon" />
    </span>
  </component>
</template>

<script lang="ts">
  import classNames from 'classnames';
  import { defineComponent, PropType } from 'vue';
  import { ButtonProps } from './Button.types';

  export default defineComponent({
    name: 'Button',
    props: {
      as: {
        type: String,
      },
      href: {
        type: String,
      },
      variants: {
        type: Array as PropType<ButtonProps['variants']>,
      },
      type: {
        type: String,
      },
    },
    setup(props: ButtonProps, { slots }) {
      const hasSlot = (name: string) => !!slots[name];
      const htmlTag = (): string => {
        if (props.as) {
          return props.as;
        }
        if (props.href) {
          return 'a';
        }
        return 'button';
      };
      const variantClasses = classNames(
        props.variants?.map((variant: string) => `c-button--${variant}`)
      );
      return {
        ...props,
        hasSlot,
        htmlTag: htmlTag(),
        variantClasses,
      };
    },
  });
</script>

<style src="./Button.css"></style>
