// src/views/HomePage/HomePageConclusion.vue
<template>
  <VSection :variants="['center']">
    <template v-slot:intro>
      <p class="u-text-headline u-color-black">
        <span class="u-text-decorative">Are you ready for battle</span>?
      </p>
      <VButton href="/register" :variants="['lg:lg', 'decorative', 'invert']">
        Register Now
      </VButton>
      <!-- <VButton disabled :variants="['lg:lg', 'decorative', 'invert']">Sold Out</VButton> -->
    </template>
  </VSection>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import VButton from "~/components/VButton";
import VSection from "~/components/VSection";
import TitleBanner from "~/components/TitleBanner";

export default defineComponent({
  components: {
    VSection,
    VButton,
    TitleBanner,
  },
});
</script>

// src/views/HomePage/HomePageConclusion.tsx
import type React from 'react';
import { Button } from '../../components/Button';
import { Section } from '../../components/Section';

export const HomePageConclusion: React.FC = () => {
  const intro = (
    <>
      <p className="u-text-headline u-color-black">
        <span className="u-text-decorative">Are you ready for battle</span>?
      </p>
      <Button
        href="/register"
        variants={['lg:lg', 'decorative', 'invert']}
      >
        Register Now
      </Button>
      {/* <Button disabled variants={['lg:lg', 'decorative', 'invert']}>Sold Out</Button> */}
    </>
  );

  return (
    <Section
      variants={['center']}
      intro={intro}
    />
  );
};

export default HomePageConclusion;
