// src/views/HomePage/HomePage.tsx
import type React from 'react';
import type { HomePageProps } from './HomePage.types';
import './HomePage.css';
import { Separator } from '../../components/Separator';
import { TitleBanner } from '../../components/TitleBanner';
import { HomePageAccommodation } from './HomePageAccommodation';
import { HomePageConclusion } from './HomePageConclusion';
import { HomePageHobby } from './HomePageHobby';
import { HomePageInformation } from './HomePageInformation';
import { HomePageOverview } from './HomePageOverview';
import { HomePageSchedule } from './HomePageSchedule';
import { HomePageVenue } from './HomePageVenue';

export const HomePage: React.FC<HomePageProps> = () => {
  return (
    <>
      <TitleBanner title="A Kings of War tournament celebrating the very best of the hobby" />
      <HomePageOverview />
      <HomePageInformation />
      <HomePageHobby />
      <HomePageSchedule />
      <Separator />
      <HomePageVenue />
      <HomePageAccommodation />
      <Separator />
      <HomePageConclusion />
    </>
  );
};

export default HomePage;

// src/views/HomePage/HomePage.vue
<template>
  <TitleBanner title="A Kings of War tournament celebrating the very best of the hobby" />
  <HomePageOverview />
  <HomePageInformation />
  <HomePageHobby />
  <HomePageSchedule />
  <Separator />
  <HomePageVenue />
  <HomePageAccommodation />
  <HomePageSponsorship />
  <Separator />
  <HomePageConclusion />
</template>

<script lang="ts">
import { defineComponent } from "vue";
import TitleBanner from "~/components/TitleBanner";
import Separator from "~/components/Separator";
import HomePageOverview from "./HomePageOverview.vue";
import HomePageInformation from "./HomePageInformation.vue";
import HomePageAccommodation from "./HomePageAccommodation.vue";
import HomePageSponsorship from "./HomePageSponsorship.vue";
import HomePageSchedule from "./HomePageSchedule.vue";
import HomePageVenue from "./HomePageVenue.vue";
import HomePageConclusion from "./HomePageConclusion.vue";
import HomePageHobby from "./HomePageHobby.vue";

export default defineComponent({
  components: {
    TitleBanner,
    Separator,
    HomePageOverview,
    HomePageInformation,
    HomePageHobby,
    HomePageAccommodation,
    HomePageSponsorship,
    HomePageSchedule,
    HomePageVenue,
    HomePageConclusion,
  },
});
</script>

<style src="./HomePage.css"></style>
