// src/components/Picture/Picture.tsx
import classNames from 'classnames';
import type React from 'react';
import type { PictureProps } from './Picture.types';
import './Picture.css';

export const Picture: React.FC<PictureProps> = ({
  maintainAspectRatio = false,
  modifiers = [],
  size,
  sources,
  src,
  alt,
  backgroundColor,
  lqip,
  loading = 'lazy',
  caption,
}) => {
  const classes = classNames(
    'c-picture',
    modifiers.map((modifier: string) => `c-picture--${modifier}`),
    size?.width && size?.height && maintainAspectRatio && 'c-picture--maintain-ratio',
  );

  const aspectRatio =
    maintainAspectRatio && size?.width && size?.height
      ? `${(size.height / size.width) * 100}%`
      : undefined;

  const pictureStyle = {
    backgroundImage: lqip ? `url(${lqip})` : undefined,
    backgroundColor,
    paddingTop: aspectRatio,
  };

  const Component = caption ? 'figure' : 'div';

  return (
    <Component className={classes}>
      <picture
        style={pictureStyle}
        className="c-picture__picture"
      >
        {sources?.map((source, index) => (
          <source
            key={index}
            srcSet={source.srcset.join(',')}
            type={source.type || ''}
            media={source.media || ''}
          />
        ))}
        <img
          src={src}
          alt={alt}
          width={size?.width || ''}
          height={size?.height || ''}
          className="c-picture__image"
          loading={loading}
        />
      </picture>
      {caption && <figcaption className="c-picture__caption">{caption}</figcaption>}
    </Component>
  );
};

export default Picture;

// src/components/Picture/Picture.vue
<template>
  <component :is="caption ? 'figure' : 'div'" :class="classes">
    <picture
      :style="{
        'background-image': lqip && `url(${lqip})`,
        'background-color': backgroundColor,
        'padding-top': aspectRatio,
      }"
      class="c-picture__picture"
    >
      <template v-if="sources">
        <source
          v-for="(source, index) in sources"
          :key="index"
          :srcset="source.srcset.join(',')"
          :type="source.type"
          :media="source.media"
        />
      </template>
      <img
        :src="src"
        :alt="alt"
        :width="size?.width"
        :height="size?.height"
        class="c-picture__image"
        :loading="loading"
      />
    </picture>
    <figcaption v-if="caption" class="c-picture__caption">
      {{ caption }}
    </figcaption>
  </component>
</template>

<script lang="ts">
  import classNames from 'classnames';
  import { defineComponent, PropType } from 'vue';
  import { PictureSize, Picture, PictureSource } from './Picture.types';

  export default defineComponent({
    props: {
      alt: {
        type: String,
        required: true,
      },
      backgroundColor: {
        type: String,
      },
      caption: {
        type: String,
      },
      lqip: {
        type: String,
      },
      loading: {
        type: String,
        validator: (value: string): boolean => {
          return (value && ['lazy', 'eager'].includes(value)) || value === null;
        },
      },
      maintainAspectRatio: {
        type: Boolean,
        default: false,
      },
      modifiers: {
        type: Array as PropType<Array<string>>,
      },
      sources: {
        type: Array as PropType<Array<PictureSource>>,
      },
      size: {
        type: Object as PropType<PictureSize>,
      },
      src: {
        type: String,
        required: true,
      },
    },
    computed: {
      classes: ({ modifiers, size, maintainAspectRatio }: Picture): string => {
        return classNames(
          'c-picture',
          modifiers &&
            modifiers.map((modifier: string) => `c-picture--${modifier}`),
          size?.width &&
            size?.height &&
            maintainAspectRatio &&
            `c-picture--maintain-ratio`
        );
      },
      aspectRatio: ({
        size,
        maintainAspectRatio,
      }: Picture): string | undefined => {
        return maintainAspectRatio && size?.width && size?.height
          ? `${(size.height / size.width) * 100}%`
          : undefined;
      },
    },
  });
</script>

<style src="./Picture.css"></style>
