// src/components/Header/Header.vue
<template>
  <header class="c-header">
    <div class="c-header__presents">
      <span class="c-header__presents-label">The</span>
      <NorthernKingsLogo class="c-header__presents-logo" />
      <span class="c-header__presents-label">Present</span>
    </div>
    <div class="c-header__main">
      <div class="c-header__logo">
        <GtLogo class="c-header__logo__image" />
      </div>
      <p class="c-header__date">
        Rothwell, Leeds. <span>May 14th and 15th</span>
      </p>
      <p class="c-header__strapline u-text-uppercase">
        <img
          class="c-header__cok"
          src="../../assets/images/cok-logo.png"
          alt="Clash of Kings"
        />
        UK Regional Qualifier
      </p>
    </div>
    <div class="c-header__book-now">
      <Button
        class="c-header__book-now__sm"
        href="/"
        :variants="['sm', 'decorative', 'ghost', 'invert']"
      >
        Book your place
      </Button>
      <Button
        class="c-header__book-now__lg"
        href="/"
        :variants="['lg', 'decorative', 'ghost', 'invert']"
      >
        Book your place
      </Button>
    </div>
  </header>
</template>

<script lang="ts">
  import { defineComponent } from 'vue';
  import GtLogo from '~/assets/images/nkgt-2022-logo.svg?component';
  import NorthernKingsLogo from '~/assets/images/nk-logo-vertical.svg?component';
  import Button from '~/components/Button';

  export default defineComponent({
    components: {
      GtLogo,
      NorthernKingsLogo,
      Button,
    },
  });
</script>

<style src="./Header.css"></style>

// src/components/Header/Header.tsx
import classNames from 'classnames';
import type React from 'react';
import { Button } from '../Button';
import type { HeaderProps } from './Header.types';
import './Header.css';

// Import SVG components
import NorthernKingsLogo from '../../assets/images/nk-logo-vertical.svg?react';
import GtLogo from '../../assets/images/nkgt-2025-logo.svg?react';

export const Header: React.FC<HeaderProps> = ({ compact }) => {
  return (
    <header className={classNames('c-header', { 'c-header--compact': compact })}>
      <div className="c-header__presents">
        <span className="c-header__presents-label">The</span>
        <a href="https://thenorthernkings.com/">
          <NorthernKingsLogo className="c-header__presents-logo" />
        </a>
        <span className="c-header__presents-label">Present</span>
      </div>
      <div className="c-header__main">
        {compact ? (
          <div className="c-header__logo c-header__logo--compact">
            <a href="/">
              <GtLogo className="c-header__logo__image" />
            </a>
          </div>
        ) : (
          <>
            <div className="c-header__logo">
              <GtLogo className="c-header__logo__image" />
            </div>
            <p className="c-header__date">
              Ossett, West Yorkshire.{' '}
              <span>
                June 21<sup>st</sup> and 22<sup>nd</sup>
              </span>
            </p>
            {/* <p className="c-header__strapline u-text-uppercase">Sorry, the event has now sold out</p> */}
          </>
        )}
      </div>
      <div className="c-header__book-now">
        <Button
          className="c-header__book-now__action"
          href="/register"
          variants={['sm', 'lg:lg', 'decorative', 'ghost', 'invert']}
        >
          Register Now
        </Button>
        {/* <Button disabled variants={['sm', 'lg:lg', 'decorative', 'ghost', 'invert']}>
          Sold Out
        </Button> */}
      </div>
    </header>
  );
};

export default Header;
