// src/components/Section/Section.vue
<template>
  <component :is="htmlTag" :class="['c-section', variantClasses]">
    <header v-if="title" class="c-section__header o-container">
      <component
        :is="leadSection ? 'h1' : 'h2'"
        class="c-section__title u-text-headline"
      >
        {{ title }}
      </component>
    </header>
    <div class="c-section__inner l-container">
      <slot />
    </div>
    <footer class="c-section__footer" v-if="hasSlot('footer')">
      <slot name="footer" />
    </footer>
  </component>
</template>

<script lang="ts">
  import classNames from 'classnames';
  import { defineComponent, PropType } from 'vue';
  import { SectionProps } from './Section.types';

  export default defineComponent({
    name: 'Section',
    props: {
      title: {
        type: String,
      },
      variants: {
        type: Array as PropType<Array<string>>,
      },
      as: {
        type: String,
      },
      leadSection: {
        type: Boolean,
      },
    },
    setup(props: SectionProps, { slots }) {
      const hasSlot = (name: string) => !!slots[name];
      const htmlTag = props.as || (props.title ? `section` : `div`);
      const variantClasses = classNames(
        props.variants?.map((variant: string) => `c-section--${variant}`)
      );
      return {
        ...props,
        hasSlot,
        htmlTag,
        variantClasses,
      };
    },
  });
</script>

<style src="./Section.css"></style>

// src/components/Section/Section.tsx
import classNames from 'classnames';
import type React from 'react';
import type { SectionProps } from './Section.types';
import './Section.css';

export const Section: React.FC<SectionProps> = ({
  title,
  intro,
  variants = [],
  children,
  className,
  ...props
}) => {
  const Component = 'div';
  const variantClasses = classNames(variants.map((variant: string) => `c-section--${variant}`));

  return (
    <Component
      {...props}
      className={classNames('c-section', variantClasses, className)}
    >
      <div className="c-section__inner l-container">
        {title && (
          <div className="c-section__header">
            <h2 className="c-section__title">{title}</h2>
          </div>
        )}
        {intro && <div className="c-section__intro l-flow">{intro}</div>}
        <div className="c-section__body l-flow">{children}</div>
      </div>
    </Component>
  );
};

export default Section;
