// src/components/TitleBanner/TitleBanner.vue
<template>
  <div class="c-title-banner">
    <component :is="as || 'h1'" class="c-title-banner__title u-text-headline">
      {{ title }}
    </component>
    <Separator class="c-title-banner__separator" />
  </div>
</template>

<script lang="ts">
  import classNames from 'classnames';
  import { defineComponent, PropType } from 'vue';
  import Separator from '~/assets/images/separator.svg?component';
  import { TitleBannerProps } from './TitleBanner.types';

  export default defineComponent({
    name: 'TitleBanner',
    components: {
      Separator,
    },
    props: {
      title: {
        type: String,
      },
      variants: {
        type: Array as PropType<Array<string>>,
      },
      as: {
        type: String,
      },
    },
    setup(props: TitleBannerProps) {
      const variantClasses = classNames(
        props.variants?.map((variant: string) => `c-title-banner--${variant}`)
      );
      return {
        ...props,
        variantClasses,
      };
    },
  });
</script>

<style src="./TitleBanner.css"></style>

// src/components/TitleBanner/TitleBanner.tsx
import classNames from 'classnames';
import React from 'react';
import type { TitleBannerProps } from './TitleBanner.types';
import './TitleBanner.css';

// Import SVG component
import SeparatorSvg from '../../assets/images/separator.svg?react';

export const TitleBanner: React.FC<TitleBannerProps> = ({ title, variants = [], as }) => {
  const Component = as || 'h1';
  const variantClasses = classNames(
    variants.map((variant: string) => `c-title-banner--${variant}`),
  );

  return (
    <div className={classNames('c-title-banner', variantClasses)}>
      {React.createElement(
        Component,
        { className: 'c-title-banner__title u-text-headline u-text-decorative' },
        title,
      )}
      <div className="c-title-banner__separator">
        <SeparatorSvg />
      </div>
    </div>
  );
};

export default TitleBanner;
